// client-nuxt/pages/index.vue
<template>
<div class="flex w-full gap-3 p-6 flex-wrap">
<div @click="postDetails(post.id)" v-for="post in posts" :key="post.id" class="card border border-secondary cursor-pointer p-2 w-96 bg-base-100 shadow-xl">
  <div class="card-body">
    <h2 class="card-title">{{post.title}}</h2>
    <p>{{post.content}}</p>

    <h6>{{post.author.fullName}}</h6>

    <button @click.stop="deletePost(post.id)" class="btn btn-primary" >Delete</button>

  </div>
</div>
</div>
</template>

<script lang="ts">


export default {
  name: 'IndexPage',
  middleware: 'auth',

  data() {
    return {
      posts: [],
    }
  },

  // computed : { use it to get reactive data .
  //   somethng(haha) {
  //     console.log(haha)
  //     return this.posts.length + " " + haha
  //   }

  // },

  methods: {
    postDetails(id) {
      this.$router.push('/posts/' + id)
    },

    async deletePost (id) {
      try {
        await this.$axios.delete(`/api/v1/posts/delete/${id}`)
        //  console.log(data)
        this.posts = this.posts.filter(post => post.id !== id)


      } catch (err) {
        console.log(err)
        // console.log(err)
      }
    }


  },

  // watch : { //watch the variable and do something when it changes
  //   posts (newOne, oldOne) {
  //     console.log(newOne.length)
  //     console.log(oldOne.length)

  //   }

  // },


  async asyncData({ $axios }) {
      try {
        const { data } = await $axios.get('http://okay.blogs.com/api/v1/posts/all')
        return {
          posts: data.posts,
        }

      } catch (err) {
        console.log(err)
        // console.log(err)
      }

    // if (process.server) {

  },


}
</script>

// client/pages/index.tsx
import type { GetServerSideProps } from 'next'
import axios from 'axios'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { useAppDispatch , useAppSelector} from "../store/hooks"
import {postAdd, postRemove} from '../store/postSlice'
interface PostInterface {
  id: number
  title: string
  content: string
  author: {
    id: number
    userId: number
    email: string
    fullName: string
  }
}
interface PropsType {
  isLogin: boolean
  posts:  {
    status : string,
    postCount : number,
    posts : PostInterface[]}
}

const Home = (props : PropsType) => {
  const router = useRouter()
  const dispatch = useAppDispatch()
  const [isLoading, setIsLoading] = useState(false)
  const posts = useAppSelector(state => state.posts.posts) 
  useEffect(() => {
    dispatch(postAdd(props.posts.posts as PostInterface[]))
    
  }, [])

  const deleteHandler = (id : number) => {
    setIsLoading(true)
    try {
      axios.delete(
        `/api/v1/posts/delete/${id}`
      )
      dispatch(postRemove(id))
        setIsLoading(false)

    }catch (err) {
      console.log(err)
                setIsLoading(false)

    
     }

    
  }

  return (
    <div className="d-flex p-4  mt-4 gap-4" >
      {posts.length != 0 &&
        posts.map((post) => {
          return (
            <div
              style={{ cursor: "pointer" }}
              onClick={() => router.push(`/posts/${post.id}`)}
              key={post.id}
              className="border  p-2 rounded-2 border-dark shadow-lg "
            >
              <h1>{post.title}</h1>
              <p>{post.content}</p>
              <p>{post.author.fullName}</p>

              <button
                onClick={(e) => {e.stopPropagation; deleteHandler(post.id)}}
                className="btn btn-danger"
              >
                <span
                  className={`${
                    isLoading
                      ? "spinner-border spinner-border-sm"
                      : ""
                  }`}
                  role="nothing"
                  aria-hidden="true"
                ></span>
                Delete
              </button>
            </div>
          )
        })}
    </div>
  )
}
//
export default Home

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  
  if (!req.cookies.session) {
    return {
      redirect: {
        destination: "/login",
      },
      props: { isLogin: false, posts : [] },
    }
  }

  const { data } = await axios.get(
    "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/v1/posts/all",
    {
      headers: req.headers as any,
    }
  )


  return {
    props: { isLogin: true, posts: data || [] },
  }
}
