// client-nuxt/pages/login.vue
<template>
  <div class="flex items-center content-center justify-center w-full">

  <FormulateForm
    name="login"
    @submit="loginHandler"
    v-model="form"
    class="login-form"
  >
    <h2 class="form-title">Login</h2>
    <FormulateInput
      name="email"
      placeholder="Put your email"
      label="Email"
      validation="required|email"
    />
    <FormulateInput
      name="password"
      label="Password"
      type="password"
      placeholder="Put your password"
      validation="required|min:6"
    />
    <FormulateErrors />

      <div class="flex flex-col d-flex mt-4">
          <button :disabled="!form.email || !form.password" type="submit" :class="[ isLoading ? 'loading' : 'something' ,'btn btn-secondary']">
            Login
          </button>

        </div>

         <div class="mt-4">
          <nuxt-link class="text-primary mt-2" to="/signup">Don't have an account?</nuxt-link>
        </div>
  </FormulateForm>
  </div>
</template>

<script>

export default {
  name: 'LoginPage',
  middleware : "notauth",
  data() {
    return {
      form: {
        email: '',
        password: '',
      },
      isLoading: false,
    }
  },

  methods: {
    async loginHandler() {
      try {
        this.isLoading = true
        const { data } = await this.$axios.post('/api/v1/auth/login', this.form)
        // console.log(data)
        this.$store.commit('setUser', data.user)
        this.isLoading = false
        // console.log(data)
        localStorage.setItem('user', JSON.stringify(data.user.userData))
        this.$router.push('/')
      } catch (err) {
        console.log(err)
        const errors = err.response.data.errors
        this.$toast.error(errors[0].message)
        this.isLoading = false
      }
    },
  },


}
</script>

<style>
.actions {
  display: flex;
  margin-bottom: 1em;
  margin-top: 1em;
}
.actions .formulate-input {
  margin-right: 1em;
  margin-bottom: 0;
}

.login-form {
  margin-top: 20px;
  padding: 2em;
  border: 1px solid #a8a8a8;
  border-radius: 0.5em;
  max-width: 500px;
  box-sizing: border-box;
  outline: none !important;
}

.formulate-input-element {
  border: 1px solid #a8a8a8;
  border-radius: 0.5em;
  padding: 0.5em;
}

.formulate-input-element input {
  outline: none;
}
.formulate-input-error {
  color: red;
}

.form-title {
  margin-bottom: 20px;
  font-size: 25px;
  text-align: center;
  font-weight: bolder;
}
</style>

// client/pages/login.tsx
import { GetServerSideProps, NextPage } from "next"
import Link from "next/link"
import React from "react"
import { useFormik } from "formik"
import * as Yup from "yup"
import axios from "axios"
import { useQuery } from "react-query"
import { ErrorInterface } from "../utils/ErrorInterface"
import { useRouter } from "next/router"
import { useAppDispatch } from "../store/hooks"
import { login } from "../store/userSlice"

const Login: NextPage = () => {
  const dispatch = useAppDispatch()

  const router = useRouter()

  const queryLogin = async () => {
    const { data } = await axios.post("/api/v1/auth/login", {
      ...formik.values,
    })
    dispatch(login({ user: data.user.userData }))

    localStorage.setItem("user", JSON.stringify(data.user.userData))

    return data
  }

  const handleLogin = async () => {
    loginInfo.refetch()
  }

  const loginInfo = useQuery("login", queryLogin, {
    enabled: false,
    refetchOnWindowFocus: false,
    retry: false,
  })

  const errorInfo = loginInfo.error as ErrorInterface

  if (loginInfo.isSuccess) router.push("/")

  // if (loginInfo.error) console.log(loginInfo.error)

    const formik = useFormik({
      initialValues: {
        email: "",
        password: "",
      },
      validationSchema: Yup.object({
        email: Yup.string()
          .email("Invalid email address")
          .required("Email is required"),
        password: Yup.string()
          .min(8, "Password must be at least 8 characters")
          .required("Password is required"),
      }),
      onSubmit: handleLogin,
    })

  if (loginInfo.isSuccess) console.log("succesfully loggred in")

  return (
    <>
      <div className="container-fluid min-vh-90 overflow-hidden">
        <div className="row mt-3 h-100 justify-content-center g-sm-2">
          <div className="col d-flex flex-column min-vh-50 align-items-center justify-content-center col-sm-8 col-md-6 col-lg-5   p-2 ">
            <h4>Login</h4>

            {loginInfo.isError && (
              <div className="alert alert-danger px-1 py-1 " role="alert">
                {errorInfo.response.data.errors[0].message}
              </div>
            )}

            {loginInfo.isSuccess && (
              <div className="alert alert-success px-1 py-1 " role="alert">
                Redirecting to the main page....
              </div>
            )}

            <div>
              <form
                onSubmit={formik.handleSubmit}
                className="d-flex flex-column"
              >
                <label htmlFor="email" className="form-label">
                  Email :{" "}
                </label>
                <input
                  type="email"
                  id="email"
                  className="form-control"
                  name="email"
                  placeholder="Enter your email"
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  value={formik.values.email}
                />
                {formik.touched.email && formik.errors.email ? (
                  <div className="text-danger">{formik.errors.email}</div>
                ) : null}
                <label htmlFor="password" className="form-label">
                  Password :{" "}
                </label>
                <input
                  type="password"
                  id="password"
                  className="form-control"
                  name="password"
                  placeholder="Enter your password"
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  value={formik.values.password}
                />
                {formik.touched.password && formik.errors.password ? (
                  <div className="text-danger">{formik.errors.password}</div>
                ) : null}

                <button
                  type="submit"
                  disabled={loginInfo.isLoading}
                  className="btn mt-2 btn-primary"
                >
                  <span
                    className={`${
                      loginInfo.isLoading
                        ? "spinner-border spinner-border-sm"
                        : ""
                    }`}
                    role="nothing"
                    aria-hidden="true"
                  ></span>
                  Login
                </button>
              </form>
              <div className="mt-2">
                <Link href="/signup">Don&apos;t have an account?</Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Login

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  // console.log(req.cookies.session)
  if (req.cookies.session) {
    return {
      redirect: {
        destination: "/",
      },
      props: { isLogin: true },
    }
  }
  return {
    props: { isLogin: false },
  }
}
