// client/components/base/Header.tsx
import React from 'react'
import Link from 'next/link'

const Header = () => {
  return (
    <>
      <div className="border min-h-50">
        <div className="border min-vh-20  w-100 flex flex-row d-flex align-items-center justify-content-between ">
          <h5  className='px-4'>Micro-BLOG</h5>

          <div className="px-5 hstack gap-4">
            <Link href={"/login"}>
              <button type="button" className="btn  btn-primary">
                Login
              </button>
            </Link>
            <Link href={"/signup"}>
              <button type="button" className="btn  btn-outline-primary">
                Signup
              </button>
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}

export default Header;

// client-nuxt/components/Header.vue
<template>
  <div class="navbar  border">
    <div class="flex-1">
      <nuxt-link to="/">
        <a class="btn btn-ghost normal-case text-xl">Micro-Blog</a>
      </nuxt-link>
    </div>
    <div class="flex-none">
      <div class="menu menu-horizontal gap-2 mr-4">
        <nuxt-link to="/login">
          <a class="btn btn-md btn-primary">Login</a>
        </nuxt-link>
        <nuxt-link to="/signup">
          <a class="btn btn-md btn-ghost">Signup</a>
        </nuxt-link>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Header',
}
</script>
