// client/pages/add-post.tsx
import axios from 'axios'
import { GetServerSideProps } from 'next'
import { useRouter } from 'next/router'
import React, { useState } from 'react'
import { useAppSelector } from '../store/hooks'

type Props = {}

const AddPost = (props: Props) => {
    const [title, setTitle] = useState('')
    const [content, setContent] = useState('')
    const author = useAppSelector(state => state.users.user)
    const [isLoading, setIsLoading] = useState(false)
    const router = useRouter()
    const createPostHandler = async () => {
        setIsLoading(true)
        try {
            const post = {
              title,
              content,
              author: {
                userId : author!.id,
                ...author,
              },
            }

            const { data } = await axios.post("/api/v1/posts/create", post, {withCredentials : true})
            console.log(data)
            setIsLoading(false)
            router.push("/")
            
        } catch (error) {
            console.log(error)
                        setIsLoading(false)

        }
            
        
        
    } 
  return (
    <div className="d-flex justify-content-center align-items-center h-100">
      <div style={{ maxWidth: "700px", width: "650px" }} className="p-4">
        <form
          onSubmit={(e) => {
            e.preventDefault()
            createPostHandler()
          }}
          className="d-flex flex-column"
        >
          <label htmlFor="title" className="form-label">
            Title :{" "}
          </label>
          <input
            type="title"
            id="title"
            className="form-control"
            name="title"
            placeholder="Title here..."
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />

          <label htmlFor="password" className="form-label">
            Content :{" "}
          </label>
          <textarea
            id="content"
            className="form-control"
            name="content"
            placeholder="Describe you post here..."
            value={content}
            onChange={(e) => setContent(e.target.value)}
          />
          <button type="submit" className="btn mt-2 btn-primary">
            {" "}
            <span
              className={`${
                isLoading ? "spinner-border spinner-border-sm" : ""
              }`}
              role="nothing"
              aria-hidden="true"
            ></span>
            Submit{" "}
          </button>
        </form>
      </div>
    </div>
  )

}

export default AddPost

export const getServerSideProps: GetServerSideProps = async ({
  req,
  res,
  params,
}) => {
  if (!req.cookies.session) {
    return {
      redirect: {
        destination: "/login",
      },
      props: { isLogin: false },
    }
  }

  

  return {
    props: { isLogin: true },
  }
}

// client-nuxt/pages/add-post.vue
<template>
  <div class="flex items-center justify-center">
    <FormulateForm
      name="login"
      @submit="addPost"
      v-model="form"
      class="login-form"
    >
      <FormulateInput
        name="title"
        placeholder="Place your title here..."
        label="Title"
        validation="required|min:6"
      />
      <FormulateInput
        name="content"
        label="Content"
        type="textarea"
        placeholder="Describe your post..."
        validation="required|min:6"
      />
      <FormulateErrors />

      <div class="flex flex-col d-flex mt-4">
        <button
          :disabled="!form.title || !form.content"
          type="submit"
          :class="[isLoading ? 'loading' : 'something', 'btn btn-secondary']"
        >
          Submit
        </button>
      </div>
    </FormulateForm>
  </div>
</template>

<script lang="ts">
export default {
  name: 'AddPostPage',
  middleware: 'auth',

  data() {
    return {
      form: {
        title: '',
        content: '',
      },
      isLoading: false,
      user: this.$store.state.user,
    }
  },

  methods: {
    async addPost() {
      try {
        this.isLoading = true
        await this.$axios.post('/api/v1/posts/create', {...this.form, author : {userId : this.user.id , ...this.user}})
        // console.log(data)
        this.$router.push('/')
      } catch (err) {
        console.log(err)
        this.isLoading = false
        // console.log(err)
      }
    },
  },
}
</script>

<style>
.actions {
  display: flex;
  margin-bottom: 1em;
  margin-top: 1em;
}
.actions .formulate-input {
  margin-right: 1em;
  margin-bottom: 0;
}

.login-form {
  margin-top: 20px;
  padding: 2em;
  border: 1px solid #a8a8a8;
  border-radius: 0.5em;
  width: 500px;
  box-sizing: border-box;
  outline: none !important;
}

.formulate-input-element {
  border: 1px solid #a8a8a8;
  border-radius: 0.5em;
  padding: 0.5em;
}

.formulate-input-element input {
  outline: none;
}
.formulate-input-error {
  color: red;
}

.form-title {
  margin-bottom: 20px;
  font-size: 25px;
  text-align: center;
  font-weight: bolder;
}
</style>
